### ISSUE TITLE
Issue after upgrading to Espressif V4.4.0

### ISSUE THREAD

**Issue by prosd** [peterus/ESP-FTP-Server-Lib#15]
Hi,

I'm experiencing an issue after I upgraded the Espressif platform from V3.X to V4.4:

`In file included from .pio/libdeps/lolin_d32_pro/ESP-FTP-Server-Lib/src/FTPCommand.h:7,
                 from .pio/libdeps/lolin_d32_pro/ESP-FTP-Server-Lib/src/FTPConnection.h:7,
                 from .pio/libdeps/lolin_d32_pro/ESP-FTP-Server-Lib/src/ESP-FTP-Server-Lib.h:8,
                 from src/global.h:262,
                 from src/main.cpp:4:
.pio/libdeps/lolin_d32_pro/ESP-FTP-Server-Lib/src/FTPFilesystem.h: In member function 'virtual fs::FileImplPtr FTPFileImpl::openNextFile(const char*)':
.pio/libdeps/lolin_d32_pro/ESP-FTP-Server-Lib/src/FTPFilesystem.h:84:46: error: invalid new-expression of abstract class type 'FTPFileImpl'
   return fs::FileImplPtr(new FTPFileImpl(next));
                                              ^
.pio/libdeps/lolin_d32_pro/ESP-FTP-Server-Lib/src/FTPFilesystem.h:40:7: note:   because the following virtual functions are pure within 'FTPFileImpl':
 class FTPFileImpl : public fs::FileImpl
       ^~~~~~~~~~~
In file included from .pio/libdeps/lolin_d32_pro/ESP-FTP-Server-Lib/src/FTPFilesystem.h:6,
                 from .pio/libdeps/lolin_d32_pro/ESP-FTP-Server-Lib/src/FTPCommand.h:7,
                 from .pio/libdeps/lolin_d32_pro/ESP-FTP-Server-Lib/src/FTPConnection.h:7,
                 from .pio/libdeps/lolin_d32_pro/ESP-FTP-Server-Lib/src/ESP-FTP-Server-Lib.h:8,
                 from src/global.h:262,
                 from src/main.cpp:4:
C:/Users/user/.platformio/packages/framework-arduinoespressif32/libraries/FS/src/FSImpl.h:39:18: note:  'virtual bool fs::FileImpl::setBufferSize(size_t)'
     virtual bool setBufferSize(size_t size) = 0;
                  ^~~~~~~~~~~~~`

Fyi: using PlatformIo

Thanks!

**Comment by peterus** [comment]
fixed with #16 release 0.11.0 already created, push to platformio library pending
